# Generated by Django 4.2.6 on 2023-11-04 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diagnoSym", "0002_symptoms"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Symptoms",
        ),
    ]
