# Generated by Django 4.2.6 on 2023-11-04 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diagnoSym", "0003_delete_symptoms"),
    ]

    operations = [
        migrations.CreateModel(
            name="Symptoms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symptom", models.CharField(max_length=100)),
                ("value", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="diagnoSym.user"
                    ),
                ),
            ],
        ),
    ]
