# Generated by Django 4.2.6 on 2023-11-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnoSym", "0017_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="disease",
            field=models.CharField(default="Allergy", max_length=100),
        ),
    ]
