# Generated by Django 4.2.6 on 2023-11-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diagnoSym", "0018_doctor_disease"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Doctor",
        ),
    ]
