# Generated by Django 4.2.6 on 2023-11-27 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diagnoSym", "0019_delete_doctor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Symptoms",
        ),
    ]
